name: Keep Streamlit App Awake

on:
  schedule:
    
    - cron: "0 0 */2 * *"
  workflow_dispatch: 
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -s https://credit-risk-dashboard-deploy.streamlit.app/ > /dev/null
